<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>libsurvive_ros2</name>

  <version>0.0.2</version>

  <description>libsurvive driver for ROS2</description>

  <maintainer email="andrew.c.symington@gmail.com">Andrew Symington</maintainer>

  <license>MIT</license>

  <author email="andrew.c.symington@gmail.com">Andrew Symington</author>
  <author email="shkwon@tommoro.ai">Sunghyun Kwon</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <build_depend>eigen</build_depend>
  <build_depend>git</build_depend>
  <build_depend>libusb-1.0-dev</build_depend>
  <build_depend>zlib</build_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>diagnostic_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>libusb-1.0</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>zlib</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
